### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dalareo** [vigneshjayavel/airbnb-rails-clone#1]
After "bundle install" && "bundle exec rake db:migrate" I get:

/home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake/alt_system.rb:32:in `<module:AltSystem>': uninitialized constant Rake::AltSystem::Config (NameError)
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake/alt_system.rb:31:in`<top (required)>'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake/win32.rb:3:in `require'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake/win32.rb:3:in`module:Rake'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake/win32.rb:2:in `<top (required)>'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake.rb:41:in`require'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/lib/rake.rb:41:in `<top (required)>'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/bin/rake:26:in`require'
    from /home/david/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rake-0.8.7/bin/rake:26:in `<top (required)>'
    from /home/david/.rbenv/versions/2.2.1/bin/rake:23:in`load'
    from /home/david/.rbenv/versions/2.2.1/bin/rake:23:in `<main>'

**Comment by vigneshjayavel** [comment]
please use ruby 1.9.3 and rails 2.3.18

**Comment by dalareo** [comment]
Thank you!!
